name: HTML Validator

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  validate-html:
    runs-on: ubuntu-latest
    steps:
      - name: Validate HTML
        uses: Cyb3r-Jak3/html5validator-action@master
        with:
          root: /
