name: HTML Validator 2

on:
  push:
    branches: ["main", "test"]
  workflow_dispatch:

jobs:
  validate-html:
    runs-on: ubuntu-latest
    steps:
      - name: Install html5validator using pip
        run: pip install html5validator
      - name: Validate HTML using the command line tool of html5validator
        run: html5validator --root ${{ github.workspace }}
